apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: microservice-user
  name: microservice-user
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: microservice-user
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml
        kompose.version: 1.28.0 (c4137012e)
      creationTimestamp: null
      labels:
        io.kompose.network/spring-net: "true"
        io.kompose.service: microservice-user
    spec:
      containers:
        - image: imanileemans/user-microservice-user
          name: microservice-user
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
