version: '3.8'

services:
  microservice-user:
    image: imanileemans/user-microservice-microservice-user
    container_name: microservice-user
    build:
      context: /
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database-user:3306/userdb?allowPublicKeyRetrieval=true&autoReconnect=true&useSSL=false
    depends_on:
      - database-user
    networks:
      - spring-net
  database-user:
    image: mysql:latest
    container_name: database-user
    environment:
      - MYSQL_DATABASE=userdb
      - MYSQL_ROOT_USERNAME=root
      - MYSQL_ROOT_PASSWORD=m@nipassword
    ports:
      - "3306:3306"
    networks:
      - spring-net
    volumes:
      - userdata:/var/lib/mysql
      - userdata:/etc/mysql/conf.d
networks:
  spring-net:
    name: spring-net
    driver: bridge
volumes:
  userdata: