# This is a basic workflow to help you get started with Actions

name: ZAP Security Scan

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    defaults:
     run:
      working-directory: ./user-microservice

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: OWASP ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.3.0
        with:
          token: ${ github.token } 
          target: "https://blog.logrocket.com/docker-sql-server/"
          docker_name: owasp/zap2docker-stable
          issue_title: ZAP Full Scan Report
          fail_action: pass
          allow_issue_writing: false
